# Generated by Django 3.2.12 on 2022-10-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('jobrole', models.CharField(choices=[('0', 'Select'), ('1', 'React Developer'), ('2', 'Node.js Developer'), ('3', 'Vue.js Developer')], max_length=30)),
                ('experience', models.CharField(choices=[('0', 'Fresher'), ('1', '0-2 years'), ('2', '3-6 years'), ('3', '7+ years')], max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
