# Generated by Django 3.2.12 on 2022-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_formdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetails',
            name='jobrole',
            field=models.CharField(choices=[('0', 'Select'), ('React Developer', 'React Developer'), ('Node.js Developer', 'Node.js Developer'), ('Vue.js Developer', 'Vue.js Developer')], max_length=30),
        ),
    ]
