# Generated by Django 3.2.12 on 2022-10-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_formdetails_jobrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetails',
            name='jobrole',
            field=models.CharField(choices=[('React Developer', 'React Developer'), ('Node.js Developer', 'Node.js Developer'), ('Vue.js Developer', 'Vue.js Developer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formdetails',
            name='linkedin',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
